### ISSUE TITLE
winscard 0.2.x blocks downstream sqlx 0.8 / picky upgrade chain (TryCryptoRng trait bound)

### ISSUE THREAD

**Issue by tippyentertainment** [Devolutions/sspi-rs#662]
Hi — filing this as a follow-on to #537 since it's a fresh manifestation of the same RC-dependency-churn problem, with a concrete blocker for downstream users patching RUSTSEC advisories.

## Symptom

Compilation fails inside `winscard 0.2.3`'s `Dummy` RNG type when the broader dep tree advances to a `crypto-bigint` that requires `TryCryptoRng`:

```
error[E0277]: the trait bound `Dummy: crypto_bigint::rand_core::TryCryptoRng` is not satisfied
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winscard-0.2.3/src/scard.rs:434:13
    |
432 |         let signature = rsa::hazmat::rsa_decrypt_and_check(
    |                         ---------------------------------- required by a bound introduced by this call
433 |             &rsa_private_key,
```

`winscard 0.3.x` is already published on crates.io and has the newer trait impls, but `sspi 0.18.x` hard-pins `winscard 0.2.x` (no feature flag to disable the smartcard dep), so downstream consumers can't pick up the fix.

## Repro

A Cargo.toml with both sspi and a sqlx 0.8 / picky 7.0.0-rc.22+ chain in the same workspace:

```toml
[dependencies]
sspi = "0.18"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-native-tls", "macros", "migrate"] }
picky = "=7.0.0-rc.22"   # newest that resolves; rc.23 wants =0.13.0-rc.2 hmac
ironrdp-connector = { path = "patches/ironrdp-connector" }  # any consumer that pins picky
```

Cargo resolves `crypto-bigint` to a version that requires `TryCryptoRng`, breaks compile in upstream `winscard 0.2.3`.

## Downstream impact

Blocks the following advisory remediations for any project that depends on both sspi and sqlx:

- `RUSTSEC-2024-0363` — sqlx 0.7 binary-protocol misinterpretation (fixed in 0.8.1)
- `RUSTSEC-2026-0098`, `RUSTSEC-2026-0099`, `RUSTSEC-2026-0104` — three rustls-webpki@0.101.7 advisories (cleared once sqlx pulls newer rustls)

In our codebase (a multi-tenant VDI control plane that uses sspi for both CredSSP and a new WinRM Negotiate dispatcher), we documented this chain in our internal triage and currently have to suppress those four advisories with a comment pointing at this upstream blocker, despite the patches existing.

## Suggested path

Bump winscard 0.2.x → 0.3.x in sspi's hard-deps (or feature-gate winscard so consumers who don't need smartcard support can disable it). The latter is more invasive but would help everyone — many sspi users (CredSSP / Negotiate auth paths) don't touch winscard at all.

## What I tried locally

- Disabling smartcard support via sspi features — there's no `scard` feature flag; winscard is unconditional.
- Vendoring a patched winscard — diverges security-critical crypto from upstream advisories, net regression.
- Pinning picky to an older version that doesn't pull the newer crypto-bigint — works, but reintroduces #537's RC-churn problem.

Happy to test a PR or pre-release branch if you produce one. Thanks for the work on sspi.

Related:
- #537 (closed) — meta-issue on RC-dep churn
- #515 (closed) — earlier RustCrypto trait-change manifestation

**Comment by CBenoit** [comment]
Hello,

We should have avoided publishing non-rc versions relying on rc version of some crates, we’ll be careful to not make this same mistake again in the future.

As for the problem at hand, sspi-rs’s latest version is v0.21 and already depends on winscard v0.3.
Did you try using the latest version?

I’m also okay with feature-gating smartcard support although I would address that as a separate issue from the compilation issue.

**Comment by jose-pr** [comment]
Following up with fresh data, since sspi 0.21.3 is now out and I tested the exact upgrade path.

**Answer to your question: yes for winscard, no for picky — and picky is now the binding constraint.**

`winscard` is resolved: sspi 0.21.3 pulls winscard 0.3.3 and the `TryCryptoRng` compile error is gone. Thank you.

But the RC chain is still not escapable downstream, because **every published `sspi` pins `picky` with `=`**:

| sspi | requires |
|---|---|
| 0.21.3 (latest) | `picky =7.0.0-rc.25` |
| 0.21.2 | `=7.0.0-rc.25` |
| 0.21.1 | `=7.0.0-rc.25` |
| 0.21.0 | `=7.0.0-rc.23` |
| 0.20.x | `=7.0.0-rc.22/23` |

Meanwhile picky-rs #512 ("move RustCrypto crates to stable releases and drop obsolete pins") merged 2026-07-17 and shipped as **picky 7.0.0-rc.26** on 2026-07-21, which moves `ed25519-dalek`, `p256`/`p384` and `aes-gcm` to unpinned stable ranges. Only `rsa =0.10.0-rc.18` remains RC there.

So the fix exists one level up and cannot be reached: no published sspi permits rc.26, and the `=` pin means downstream cannot override it.

**Concretely, what this blocks.** I maintain a Rust workspace with an IronRDP-based RDP backend and a russh-based SSH backend. They cannot share a lockfile:

| crate | russh resolves | picky rc.25 forces |
|---|---|---|
| `curve25519-dalek` | **5.0.0** (stable) | `=5.0.0-rc.1` |
| `ed25519-dalek` | **3.0.0** (stable) | `3.0.0-rc.1` |
| `ecdsa` | **0.17.0** (stable) | `0.17.0-rc.22` |
| `p256` | **0.14.0** (stable) | `0.14.0-rc.14` |
| `rsa` | 0.10.0-rc.18 | `=0.10.0-rc.18` (already agree) |

Every conflicting crate is one rc.26 unpins, and the single RC rc.26 keeps is the version russh already uses. So an sspi release on picky rc.26 would very likely resolve this outright.

**I verified the workaround space is empty**, rather than assuming:
- `[patch.crates-io] picky = "=7.0.0-rc.26"` → *"patch for `picky` points to the same source, but patches must point to different sources"*.
- A forced direct `picky = "=7.0.0-rc.26"` dependency → *"failed to select a version for `picky` … required by `ironrdp-connector` … versions that meet the requirements `=7.0.0-rc.25` are: 7.0.0-rc.25"*.
- Cloning IronRDP and bumping its own pin → fails at `sspi`, which is what led me back here.

So the ask is narrow: **an sspi release that permits picky 7.0.0-rc.26** (ideally with a caret rather than `=`, per your first paragraph). IronRDP can then follow with a one-line bump. Happy to open the PR against sspi if a version bump is all it needs — say the word and I will test it against the tree above first.
